language: python
#dist: trusty
#sudo: required

python:
    - "3.5"

addons:
  firefox: latest

install:
    - pip install 'django<1.9'
    - pip install --upgrade selenium

script:
    - python manage.py test lists
    - python manage.py test functional_tests
