language: python
#dist: trusty
#sudo: required

python:
    - "3.5.0"

addons:
  firefox: latest

install:
    - pip install 'django<1.9'
    - pip install --upgrade selenium

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    - python manage.py test lists
    - xvfb-run python manage.py test functional_tests
