language: python
sudo: required
python:
- '3.5'
install:
- pip install 'django<1.9'
- pip install --upgrade selenium
- pip install coveralls
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- coverage run -a manage.py test lists
- coverage run -a manage.py test functional_tests
after_success:
- coverage report
- coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_884abc9aece8_key -iv $encrypted_884abc9aece8_iv
  -in deploy_tools/deploy_key.enc -out deploy_tools/deploy_key -d
